name: Feature Request
description: File a feature request
title: "[Feature Request]: "
labels: ["enhancement"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: describe-problem
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is.
      placeholder: Tell us what you think!
      value: I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: describe-solution
    attributes:
      label: A clear and concise description of what you want to happen
      description: Help us understand your improvement ideas.
      placeholder: Tell us what you think!
      value: I have thoughts, here they are! [...]
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered. This field is markdown compatible.
  - type: textarea
    id: screenshots-and-context
    attributes:
      label: Screenshots and additional context
      description: Please upload any relevant screenshots. This field is markdown compatible.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
